config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :admin_users
      resources :posts

      root to: "users#index"
    end
  resources :posts
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates_presence_of :first_name, :last_name

  def full_name 
    last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all
    end

    def new 
        @post = Post.new
    end

    def create 
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save 
            redirect_to post, notice: 'Your post was created successfully'
        else 
            redirect_to new_post_path, notice: 'Date and Rationale cannot be empty'
        end
    end

    def edit 
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notice: 'Your post was edited successfully'
        else
            render :edit 
        end
    end

    def show 
    end

    def destroy 
        @post.delete
        redirect_to posts_path, notice: 'Your post was deleted successfully'
    end

    private 

    def post_params 
        params.require(:post).permit(:date, :rationale)
    end

    def set_post 
        @post = Post.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController


    def homepage
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def active?(path)
       "active" if current_page?(path) 
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div id="notice_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <div class="container">
	    <div class="row">
		    <div class="col-md-12">
          <%= render 'shared/nav' %>
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { role: "form" } do |f| %>
    <div class="form-group">
        <%= f.label :date, class: "col-sm-2 control-label" %>
        <%= f.date_field :date, class: "form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :rationale, class: "col-sm-2 control-label" %>
        <%= f.text_area :rationale, class: "form-control"%>
    </div>

    <%= f.submit "Save", class: 'btn btn-primary btn-block' %>

<% end %>

app/views/posts/_post.html.erb
<tr class="table-active">
    <td>
        <%= post.id %>
    </td>
    <td>
        <%= post.date %>
    </td>
    <td>
        <%= post.user.full_name %>
    </td>
    <td>
        <%= truncate(post.rationale) %>
    </td>
    <td>
        <%= link_to 'Edit', edit_post_path(post), id: "edit_#{post.id}" %>
    </td>
    <td>
        <%= link_to 'Delete', post_path(post), method: :delete, id: "delete_post_#{post.id}_from_index", data: { confirm: "Are you sure?" } %>
    </td>
</tr>

app/views/posts/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>
			    #
			</th>
			<th>
				Date
			</th>
			<th>
				User
			</th>
			<th>
				Rationale
			</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
        <%= render @posts %>
	</tbody>
</table>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

    <%= f.date_field :date %>
    <%= f.text_area :rationale %>

    <%= f.submit "Save" %>

<% end %>

app/views/posts/show.html.erb
<%= @post.inspect %>

app/views/shared/_nav.html.erb
<div class="logo">
    <h1>Time Tracker</h1>
</div>

<ul class="custom-nav nav nav-tabs">
	<li class="nav-item nav-link  <%= active?(root_path) %>">
		<%= link_to "Home", root_path %>
	</li>
	<li class="nav-item nav-link <%= active?(posts_path) %>">
		<%= link_to "Time Entries", posts_path %>
	</li>
	<li class="nav-item nav-link <%= active?(new_post_path) %>">
		<%= link_to "Add New Entry", new_post_path, id: 'new_post_from_nav' %>
	</li>
	<li class="dropdown ml-md-auto">
		<button class="btn btn-secondary dropdown-toggle active" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
        </button>
		<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to 'TODO: Admin Dashboard', root_path, class: "dropdown-item" %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
		</div>
	</li>
</ul>